import { Product, Category, Customer, Order } from './types'

export const categories: Category[] = [
  { id: '1', name: 'Carnes Defumadas', slug: 'defumadas' },
  { id: '2', name: 'Cortes Premium', slug: 'premium' },
  { id: '3', name: 'Linguiças', slug: 'linguicas' },
  { id: '4', name: 'Acompanhamentos', slug: 'acompanhamentos' },
  { id: '5', name: 'Combos', slug: 'combos' },
]

export const products: Product[] = [
  {
    id: '1',
    name: 'Brisket Defumado',
    description: 'Peito bovino defumado por 14 horas em madeira de carvalho. Casca crocante e interior suculento. Servido fatiado.',
    price: 89.90,
    category: 'defumadas',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    available: true,
  },
  {
    id: '2',
    name: 'Pulled Pork',
    description: 'Paleta suína desfiada, defumada por 12 horas. Textura macia e sabor intenso de defumação.',
    price: 59.90,
    category: 'defumadas',
    imageUrl: 'https://images.unsplash.com/photo-1623174479905-4c8efe903893?w=800&q=80',
    available: true,
  },
  {
    id: '3',
    name: 'Costela Defumada',
    description: 'Costela bovina defumada por 10 horas. Carne que solta do osso, com bark perfeito.',
    price: 79.90,
    category: 'defumadas',
    imageUrl: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800&q=80',
    available: true,
  },
  {
    id: '4',
    name: 'Picanha Premium',
    description: 'Corte nobre de picanha, maturada por 21 dias. Marmoreio excepcional.',
    price: 129.90,
    category: 'premium',
    imageUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80',
    available: true,
  },
  {
    id: '5',
    name: 'Ancho Angus',
    description: 'Corte Angus certificado, perfeito para grelhar. Sabor intenso e textura macia.',
    price: 119.90,
    category: 'premium',
    imageUrl: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=800&q=80',
    available: true,
  },
  {
    id: '6',
    name: 'Linguiça Artesanal',
    description: 'Linguiça de pernil suíno com especiarias da casa. Defumada naturalmente.',
    price: 34.90,
    category: 'linguicas',
    imageUrl: 'https://images.unsplash.com/photo-1635430666877-7b7e97f5cd2f?w=800&q=80',
    available: true,
  },
  {
    id: '7',
    name: 'Linguiça Calabresa Premium',
    description: 'Calabresa artesanal com pimenta calabresa importada. Sabor marcante.',
    price: 39.90,
    category: 'linguicas',
    imageUrl: 'https://images.unsplash.com/photo-1622944925028-a7a838953e0a?w=800&q=80',
    available: true,
  },
  {
    id: '8',
    name: 'Farofa da Casa',
    description: 'Farofa artesanal com bacon defumado, cebola caramelizada e ervas.',
    price: 19.90,
    category: 'acompanhamentos',
    imageUrl: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800&q=80',
    available: true,
  },
  {
    id: '9',
    name: 'Vinagrete Premium',
    description: 'Vinagrete fresco feito na hora com tomate, cebola e pimentão.',
    price: 14.90,
    category: 'acompanhamentos',
    imageUrl: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800&q=80',
    available: true,
  },
  {
    id: '10',
    name: 'Combo Família',
    description: 'Brisket 500g + Pulled Pork 400g + Costela 600g + 2 Acompanhamentos. Serve até 6 pessoas.',
    price: 249.90,
    category: 'combos',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    available: true,
  },
  {
    id: '11',
    name: 'Combo BBQ Master',
    description: 'Brisket 300g + Costela 400g + Linguiça 300g + Farofa. Serve até 4 pessoas.',
    price: 189.90,
    category: 'combos',
    imageUrl: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=800&q=80',
    available: true,
  },
  {
    id: '12',
    name: 'Ribeye Wagyu',
    description: 'Corte Wagyu australiano com marmoreio intenso. Experiência gastronômica única.',
    price: 249.90,
    category: 'premium',
    imageUrl: 'https://images.unsplash.com/photo-1615937657715-bc7b4b7962c1?w=800&q=80',
    available: false,
  },
]

export const mockCustomers: Customer[] = [
  {
    id: '1',
    name: 'João Silva',
    phone: '(11) 99999-1234',
    email: 'joao@email.com',
    address: {
      street: 'Rua das Flores',
      number: '123',
      neighborhood: 'Centro',
      city: 'São Paulo',
      state: 'SP',
      zipCode: '01234-567',
    },
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Maria Santos',
    phone: '(11) 98888-5678',
    email: 'maria@email.com',
    address: {
      street: 'Av. Brasil',
      number: '456',
      complement: 'Apt 12',
      neighborhood: 'Jardins',
      city: 'São Paulo',
      state: 'SP',
      zipCode: '04567-890',
    },
    createdAt: new Date('2024-02-20'),
  },
]

export const mockOrders: Order[] = [
  {
    id: 'ORD001',
    customerId: '1',
    customer: mockCustomers[0],
    items: [
      { product: products[0], quantity: 2, observations: '' },
      { product: products[7], quantity: 1, observations: 'Sem bacon' },
    ],
    subtotal: 199.70,
    deliveryFee: 10.00,
    total: 209.70,
    deliveryMethod: 'delivery',
    paymentMethod: 'square',
    status: 'preparing',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'ORD002',
    customerId: '2',
    customer: mockCustomers[1],
    items: [
      { product: products[9], quantity: 1, observations: '' },
    ],
    subtotal: 249.90,
    deliveryFee: 0,
    total: 249.90,
    deliveryMethod: 'pickup',
    scheduledDate: new Date(),
    scheduledTime: '18:00',
    paymentMethod: 'pix',
    status: 'smoking',
    createdAt: new Date(Date.now() - 3600000),
    updatedAt: new Date(),
  },
  {
    id: 'ORD003',
    customerId: '1',
    customer: mockCustomers[0],
    items: [
      { product: products[3], quantity: 1, observations: '' },
      { product: products[5], quantity: 2, observations: '' },
    ],
    subtotal: 199.70,
    deliveryFee: 10.00,
    total: 209.70,
    deliveryMethod: 'delivery',
    paymentMethod: 'cash',
    status: 'received',
    createdAt: new Date(Date.now() - 1800000),
    updatedAt: new Date(),
  },
]

export const orderStatusLabels: Record<string, string> = {
  received: 'Pedido Recebido',
  preparing: 'Em Preparo',
  smoking: 'Defumando',
  finished: 'Finalizado',
  out_for_delivery: 'Saiu para Entrega',
  delivered: 'Entregue',
}

export const orderStatusColors: Record<string, string> = {
  received: 'bg-blue-100 text-blue-800',
  preparing: 'bg-yellow-100 text-yellow-800',
  smoking: 'bg-orange-100 text-orange-800',
  finished: 'bg-green-100 text-green-800',
  out_for_delivery: 'bg-purple-100 text-purple-800',
  delivered: 'bg-gray-100 text-gray-800',
}
